package com.azizbgboss.wordle;

import javax.microedition.lcdui.*;

public class WordleGame implements CommandListener {

    // --- Word list ---

public class Words0 {
    public static final String W =
        "DOERSBLESSUNBARSPACYFARMSPLANSBONNEROIDSTANKSBELIE" +
        "SOLONYOLKSQUACKROAMSSTACKPLACEFAKESUNHIPHALEDELATE" +
        "OPTEDTYROSFETIDSMOGSNOBBYVOILASHILLADIEUPROPSNIPPY" +
        "WATSAPORESBLUESSLOSHVELDTDAREDSAWERPOREDLEFTSOILER" +
        "NASALHANKYSNARKCARTSANOLEUNHITSAPPYBUCKSLORESRHUMB" +
        "CATTYBIDEDNOSEDWARESCLADSMOONSSWEEPLODGEGLOSSBLEAR" +
        "HAWKSSHOWNLAZESDEARSBAUDSPERMSHONKYCONGAJUJUSBOOED" +
        "LARKSSPACEPAVERKAPPABLINDFLOWNALOHAGRINDMUSSYRELAY" +
        "RERANTUBEDHAMMYSQUABCAGESPRIGSCOXESFEMMEHALVESPINA" +
        "SOGGYREWEDPRIMOSANDYWHEATHAFTSDOSESNEWLYENVOIGAUSS" +
        "CANALMOVEDSATINBOOTYGAMESLACEDOWNEDPOLISSHOOTPETAL" +
        "FLIRTDEARYKNITSTRENDBORONATRIASMASHDONUTBRONCDREAM" +
        "MURKYVERSECITESGIRTSBULBSDOLTSTYKESSURFSACRESCASED" +
        "FASTSCARERGIMPSEARLYDENSETUXESBAKERFOOLSDIESTNUDES" +
        "LOVESEATERDRAPEYOGICEXERTBECKSLEERSROBEDHOOKYCLASH" +
        "PRIMPNIXEDQUICKCLAYSMOIREOXBOWDOTERAFIRETASKSREEDY" +
        "LAWNYBOILSRASPSMISERHOSESFENNYVEINYHOTLYSEXEDFRUIT" +
        "GISTSDRAINCOCASOPERAMOCKSWAIFSBREEDSOARSGIGASGIRTH" +
        "PORGYDEPTHSPANKTHUGSENVOYLACEYPAGESYEARSSWIMSLYING" +
        "RETCHMOVERSWIRLCHOSEBUTYLWISESAUDITCURVEEARLSCOWRY" +
        "VENALSTARTPOSTETAREDCLOUTDECRYPLANEPAMPAFISHYBULGY" +
        "TOOLSSHIRKREALSKIOSKASKEWSORESVAILSYEARNPEEKSROSIN" +
        "VERGEDEIGNPINTOTYPOSUMIAKBRAZEKNOCKMYNAHHAYEYLATUS" +
        "LURCHFAUNSCOWERSUEDEQOPHSFJORDTOPEDTEENSDRIBSINERT" +
        "RIGIDHEIRSAZINESTUNSLODESASKEDBOLOSCONEDCOPESPRUNE";
    public static final int COUNT = 250;
}


public class Words1 {
    public static final String W =
        "WOODSAIMEDBRATSERASEVERSOBLONDPICKYSHARDBUSTYTACKS" +
        "NECKSGLOBSSMOCKWHOOOEXECSLEGITHILARJUTESEXPELHARTS" +
        "WARTSCRUSEAGENTGRAPHMATEYPONDSLOWERSPOORSTOAEHILLY" +
        "MUSKYFOUNDGRASPSAUNATABORSHAKOCHIMEHELLOLAIRSVOTER" +
        "CILIAASSESRICERTRAWLNUMBSGUSTYGELDSHARPSSKINTSTEIN" +
        "GABLESEWEDWANLYSWAINRELAXMATZOFLOOROVENSUNFIXSHRUB" +
        "HEFTSHELLSSILKSSNIFFSNAILLOFTYBINGOHULKYCUSHYRIVER" +
        "PARESSNAGSAPISHHENNAAIDESSTUMPNEVERAFFIXTIKISTIPPY" +
        "PAINTKLIEGLUPUSBUGGYADDLESCRUMGONZOALWAYLEERYWARNS" +
        "SAILSBOFFOSEDANTAPIRBROWNCARETWALESTAGUAHOCKSGYPSY" +
        "LIMBSWADERCODESELIDELINESCOILSTOOTHCAULKDOOZYKABOB" +
        "PICOTBEAMYMUXESMUTEDMONICAUGERFROZECHIRPWHOLEKUDOS" +
        "GOUTSGILDSVYINGWROTEGERMSCOKEDCURRYFATALMODESSAHIB" +
        "CEASEFEUEDJELLYBERYLSPEAKSPINEBERRYMOTETBULKSREFER" +
        "LAWNSBANALCROUPBLOWSGULPSENROLABUZZAFTERFUDGYNIXIE" +
        "DELAYWHATSELUDEAGLOWPINGSSLABSREFLYGATESUTTERTRACK" +
        "MERITMETROQUIETTRIERHEFTYOCHREBEANSKILTSSKIEDORTHO" +
        "COMESANODEBULLYBONGSCIGARCUBICBRAWNZEROSPESKYPRATS" +
        "HOURILURESWREAKFETUSHUNKYTALCSSEWERCREMEPULLSCRESS" +
        "BAGGYWOUNDPINCHLARVAGAWKYTELLYRITESHAREMPLYERCURBS" +
        "CHEFSALTHOWILTSSPRAYEMITSCLASPIAMBSSCOLDCIVVYROOFS" +
        "REFITPLASMCOQUIBEASTEDGERDRIFTSOUPSSKIMSFIEFSLETUP" +
        "DEBUTPHYLAPUNNYPUBISBEACHPRISESURERULNASDUOMOVETCH" +
        "POXESAGLEYCRIBSCRICKCIVETHEERDFORMSCREPEHARKSBURNT" +
        "SERUMHAZEDSTAYSCAVESBASKSOVARYAWAITUNCAPTYPESWHETS";
    public static final int COUNT = 250;
}


public class Words2 {
    public static final String W =
        "LEEKSCHARYSNOWSBARFYROANSPLOWSBEEPSSHOCKMOTELTOAST" +
        "NOELSTONGSBRAKESWELLTAPERFUSEELUVYAGEEKSSHORNMOTHY" +
        "MAYORSOURSPEPPYIDIOMREBUSDESKSRADONCANESCANSTSKIPS" +
        "BOUNDROGUEPUCKSACTEDCOZENWORTSVEEPSVALVEKEYEDDOILY" +
        "CRISPTACTSHOMEDCHASEWEIRSBLUSHMOPESELEGYCRAFTOUTER" +
        "EXULTBOWLSCURESSEPIAJILTSLADEDANNOYSLIMYMANGOCLAPS" +
        "MOXIEMANIASPROGTAXISNOVAETURFYLOSSYDADOSPUBESFACES" +
        "SCOPSBUNGSTRIBSATILTSINCEMINERSHEWSWHITEENJOYTROLL" +
        "FAKIRBROTHNAIADBARERSALTSBILKSVENUEBRUNGDIPSOSWARD" +
        "BRUINDIVERHOKEYHALOSSERFSRADIXSTONEFLYERTAXONGNOME" +
        "TRAMPLEGOSGOODYSICKOGAZESSNUBSDROLLASIDERUNICPEATS" +
        "DRUNKGUAVAUNJAMTELLSBASALCLIPSPILEDSTOCKECHOSSPENT" +
        "MIENSTANGSSTOASTRIEDSORTSTARPSDYKESHEEDSFOAMSBLABS" +
        "FETALMUNGYCLIFFBUNNYRUNTYTWINKGLUEDPOUCHFUGUECAKED" +
        "REVELLOUISBADDYLANCEQUITSLARCHCOOLSBIDETTEXTSCOMAS" +
        "LAKERCAFESQUAFFOWINGAVOIDENTERDIMESTWIGSMELEETACOS" +
        "SHNORDANCEPLOYSWAXENGEODELILACLOWLYREMIXCYSTSFACET" +
        "TOPOSSTAIDPLUMBGROATCARRYSILLSSCUDSLONERFIFTYMOVES" +
        "SOMASPEEVEWANNAMEZZOAURAEYEASTFRONDSTERNEDUCETUMMY" +
        "MELTSWADEDSKIDSFIERYGNATSSTUDYFRONTFROSHABSITPRICK" +
        "ALKYDCROCSSMALLCRUFTTURBOIOTASTEAMSRAVERDIRKSKALES" +
        "HURTSCHINEINJUNOSIERUNITEGRUFFDINGYSPEWSSCAMSNITTY" +
        "HONEYREEKSSCARPSCRAMAFOOTAGAVEBEEFYIRKEDHAZERCAULS" +
        "WESTSFRIGSCAROBWRAPSCARATWINKSLAXERHOOFSHAIKURAPID" +
        "CLOYSRASAETUTORENDERSHREDSTYLILOGGYCLEFTYUCKYGUIDE";
    public static final int COUNT = 250;
}


public class Words3 {
    public static final String W =
        "EPHAHCORERUNSEETODAYCRAZYOVATEPECKSGOOFYGAMEDNISEI" +
        "YELPSPORKYLARGEBELCHMOLARNAPESCHAINNAVELSHUCKSHAFT" +
        "KEELSRINSEMAIMSDOGGYGLADSMOODYTACETHORNYBLINKBASIC" +
        "HYPOSSUMMASOOTYREPAYBATTYFRAYSNOOSEBOLTSYOBBOFIORD" +
        "MATERPRUDELEAPSPURSERATEDREARSWILCOLABELPROOFCHORE" +
        "CALLASIXESSWAMISTAVEFILERTIZZYNEATHPOLESBARGEVOGUE" +
        "NABOBITCHYDUMPSGECKOJURORIONICHUBBYFURRYSATYRMINUS" +
        "IDEALMOUTHSLAPSBYLAWMARTSCHEERMIGHTBOGGYHARUMGLUTS" +
        "THANKBIDDYEVENTCLUBSBARONPOTTYMISTSFLINGCINCHVOWER" +
        "CACTICARDSHARRYCACAOMYNASHADSTMERSEMESSYBEEFSPURLS" +
        "JUSTEPLUMYAUGHTSPURTDELLSMUTTSTREADRUSKSRENTEADULT" +
        "HAPPYSTOWSBILGYHANDSFEUARBEGANAMINOARITYFLAKEDOWDY" +
        "TAUPEUNARCBREADOAREDAWASHASKERGETUPDRANKROOSTSPEED" +
        "DIODELINGSTENCHTORTSLOCUSTONERBEVELPIPERSWILLSAYER" +
        "FISTSFINDSGOERSROBINHOTELENSUEZAPPYSTENORERUNBILGE" +
        "SCARYAISLEJIFFSINTERSWAGSHATESADMANDIZZYBALSACREEP" +
        "LARDSAMMOSSTANKLIMITNUDERSEPOYROCKYTREEDDORKYSINEW" +
        "BONESDUSTSCAVEDHYDRARUBLEDATERFERNSMICKSFUTONSWISS" +
        "BOZOSRUSESLIVESGUANOVIVASROYALCAPOSSQUIDMOGULLASSO" +
        "AFORECALVETIKESPESTSLYMPHBLOKEMAMMACUNTSVICESHINDS" +
        "SCULLUSUALSPAWNSEALSPUPPYKARATKULAKKRAALGRATASTEER" +
        "BARMSPSOASSHAYSCODASVAPIDSHAWMVILLIREACTSPECKCOWLS" +
        "TRUESPUNKYFREAKSMELLBALESKNEEDWINCEGOOKSHOUSEFLAIR" +
        "AUDIOGASESFOLIOLORDYHAVOCREDIPGAUGEGRUMPEMBERVEXES" +
        "GONERPIZZASKEETBUDDYAREALCOACHDOPERTRIBECHOKETHREW";
    public static final int COUNT = 250;
}


public class Words4 {
    public static final String W =
        "OMEGALEANTUNARMYAWLSTRIPSCHIMPNOOKSSKATESPIKYHERBY" +
        "TAXERZAYINFATLYSOUNDSHOALSTELADUNGYPAPAWKRAUTLEMMA" +
        "JANESDAUBSSLOESFINESBLUERRAZERFORKYTOKESPSEUDPUKED" +
        "MOLTOSTAIRMARLSSNACKBOCCEFLOESQUARTVOCALMASKSUNARY" +
        "LUNGSIDEASVASESDUNCEDRUGSGLOVEBUMPHLOCALOHMICSPINY" +
        "UNDIDWALTZMACESJAMBSEMENDLEAVETAROSPESTOPAPERDAIRY" +
        "GAILYSHYLYJUDGEUMBRABRIARWEALDPURERGONGSPAIRSROPER" +
        "KETCHLURKSBLOCSVOWELFRAUDAMBITFORTEALTARSKEINHARDY" +
        "DIKESRATHSTIRESOUTENDIVANDIETSEXITSAVOWSLEVEEEDICT" +
        "VIRALSAFERHOISTCUKESBEGINKLUNKVALUEDUDDYSHOATREEDS" +
        "GIMELLASERNOOKYDESEXMORAYBRAVELENTOLOTSAODOURKERNS" +
        "STOVEALIBILIPIDASSAIDECAFAWINGBIRTHWARTYWITTYMILKY" +
        "CROPSBENDSWATTSHYPERPLANKMAYSTPLEATRIGORDIRGESPIRE" +
        "ELOPERAVESALARMWRITSPAGANLASESSCANSCHAFEPIERSNERVY" +
        "CANOEAJUGANAILSRODEOGRAPEMUNCHSONLYEASESLISPSBALER" +
        "PITASVIEWSTOWNSMICROPRIVYLOOTSBOONSTIDESDOORSKILNS" +
        "VIREOTREKSJAUNTBYWAYLOAFSGUESTNATTYTWISTZIPPYFOXED" +
        "FAMEDTASTYEQUALLARGOKINDSVARIANOISEHOARDEXCONPOLIO" +
        "ACMESFAZEDQUEERRICESDOUBTDOINGTORSIGOOPYPREPSREGAL" +
        "GLYPHBUSEDFILCHSALVESLUFFMIXEDLAUDEVOUCHDEBUGSPRAT" +
        "DRAMSRULERCILLSSTETSORGANIDYLSAMISSROPESGEOIDREMAP" +
        "FETCHRIMESSWANSRIVENCLIMERUFFSMAILSDOWSELEFTYSCALD" +
        "ANTESGAMBASHIEDCHIEFWHEELTORAHHIMBODYINGDOPEDLASED" +
        "GLOMSRAGEDSWATSSPRITLADLESEEPSGAMUTAYINSDOSEDSHADE" +
        "QUESTISSUEPUSSYLLAMARILESROLESFARTSWEEDYTUFTSBUNKO";
    public static final int COUNT = 250;
}


public class Words5 {
    public static final String W =
        "DINKSDIDDYWHISHWHELMSCALYALECKBILESSHEEPCOMPSLEANS" +
        "ODDERGANGSSLITSAZOICTWEEDFOCALPUDGYSHOPSCANEDPIOUS" +
        "DEWEYSHERDHEXEDDECAYMANLYCHARMBLIMPHOSEDOLDERMALLS" +
        "SLAVEAGILEVIANDNAIVESOFTSNYLONLOONYFAIRSROMANSWAMP" +
        "CADGESIGHSPODIAPURRSBLAHSMORNSSHOEDBATESDODGYQUOTE" +
        "MAGMATIARAJELLSCUFFSCHINAJIBESAMPEDAXLESBRIMSQUIPU" +
        "FRETSPAPASTWIXTPREENAURICKELPYOVOIDFADEDMOLDYJELLO" +
        "QUOITSTIEDDOLLSBASSIKERBSBACONMECCATEATSCROCKTUNIC" +
        "CLINGPEWITFIGHTGROWLCLANKHEARDFIBERWHUMPBAYOUBILLY" +
        "SENDSNOVASSIRUPTARTSHIKERBLURBGRABSPOSERHEAPSLISLE" +
        "KAZOOANDEDLOPERSOWEDRIPERBALMYBUFFAOMITSFOLDSBURRO" +
        "WRATHASSAYSAVEDKOPEKTOWELRACKSLOAMSSLATSMUSOSHUMPY" +
        "BEAUSSIGMADISKSERODELUSTYBONDSCULTSDRUIDSTOGYSPOIL" +
        "COKESBATONFARCEJAILSTREATLIMNSTEASETITTYRINGSDRAWS" +
        "PINEYKHAKISEAMSBRINYTWANGLEASHBUYERBRAVOSOULSANISE" +
        "SAKESZEBUSHEADSUNWEDDATEDFALSECRUELREEFSBIBBSDOUSE" +
        "COASTRARERCAPEDSCOWLNERTSBOWEDSHIREOXLIPONIONVINES" +
        "IOCTLDOESTSOILSYUKKYHEAVEMETERBANDSGOONSTOADYFERRY" +
        "JAWEDMAGUSPEACERETROPROMSMALTSGROOKCOSETCULPABORIC" +
        "LYCRADHOWSKNIFESWISHTUNNYTOXICSINKSRAFTSDIEMSLOUSY" +
        "LORDSHYPEDENNUIMINDSBEINGRISKYPYGMYTHOUSWIDENWOODY" +
        "TONESFATEDLUNARHAFTAIMAGEKNOPSOASISWARPSSHAGSFLUNG" +
        "ABUTSELFINJUKESAHOLDPYXIEGREEKMINCEFICHURUINGFACIE" +
        "COPERMOUNDFOULSRUSTYDWELTSPIVSCARNESHREWPOEMSHUZZA" +
        "SOUPYCOVEYSOCLEBOULEPALLYHYENATORCHSCRODSLUMPDIVAS";
    public static final int COUNT = 250;
}


public class Words6 {
    public static final String W =
        "MALESVISTASALVOFAUNATARRYBRUNTBANDYURGESFLUIDCAPES" +
        "GRAYSDICEDPILAUMEDIADISHYROILYROGERKINDALOBESROADS" +
        "FLOURHEIGHSKEWSMATEDMODALCROONFUNGIBADLYHEATSIRONS" +
        "SUNNYCURIEWRUNGCADRELOLLYSICKSMUNGEYUCCASLIMESCANT" +
        "ROUNDIMBUESLICKSELAHSAUCEBEARDCOUNTROOMSSERVOWEEDS" +
        "BRINKUNCLEWELSHRENEWBADGECOOKSREPROILIACLEPERHIRED" +
        "YAWEDSWEETCARESUNWONARGONFLIPSNAKEDFAKEDKRILLPOSET" +
        "PITHYNAVESFLEETSHIFTBIKEDWAITSLIMENSLIERAMEBAVOTED" +
        "TASTESULKYSTRAPWHIMSEATENANGERWIRESPALEDWOOERSKULK" +
        "SHUNSUPPERCHUFFFEISTLEAKYHAIRYMUSESPRINKAPINGHONER" +
        "SOYASFORTHISLESAMENSBURLSANENTFILESLAMERULNARSPATE" +
        "DINGSLOTUSDOLEDPUMASMARCHLANKYCOHOSRINDSLOBBYCUBBY" +
        "CRINKADAPTHORSEFLAMEGRAZEVIGORWHOSOTHYMEKICKYPOESY" +
        "CRUETBEADYLEVERSEDGEMATCHDOETHBAWLSTWIRLPOLYPPHAGE" +
        "SCRUBNEARSFLOWSGROSSVEERSALONGABACIEXILEBLEBSBARDS" +
        "STRIPCOMMAALONEWISERTHETALEMONFANCYMASHYVIRUSAPSOS" +
        "BUZZYHAYEDNUKEDBUMPSTRULYKNOWNHURRYHUSKYTIROSLAUDS" +
        "ACRIDSECCOFAITHBARNSTAXOLCYNICTURDYSCUDIGLOBEEPICS" +
        "WELTSTAPESGAUNTHULASBALEDXEROXPADDYPOMPSLACEROVALS" +
        "WINGSCLUEDFRYERFLABSMANEDUNLITASSEDTECHSBELLYGROOM" +
        "OFFALMIMESPOETSFULLYCHOWSGAVELBLAMEHIPPYFAKERCHAMP" +
        "SENSEPIANOKERFSGLIDECRUDSPENDSCOATISNUCKSTATEWINED" +
        "NORTHPORNOCOOEDFUZESTINESGIVESMICASRIOTSDREADHUMPF" +
        "TOWERYOURSMARIAPREXYOBOESSALTYDUCKYCLOTHIMPLYAMUSE" +
        "CENTSNOTEDWANDSFOALSTOOTSLIMOSAVERSBUENABOSKYMOORS";
    public static final int COUNT = 250;
}


public class Words7 {
    public static final String W =
        "JERRYBASEDBRAESRASPYLABIASARGECOPRASUITSWICKSTOUCH" +
        "TOKENCAIRNTWAINBEGATSLOTHAMYLSSWIGSGOESTUNMANVOWED" +
        "SEETHGWINESCOOPTAELSGRIFTDAMPSCORNUCODEXSCRIMFLUSH" +
        "HORDEBAGELROLLSVROOMLITREGULLYBIRDSFLYBYTEPIDSLOPE" +
        "LYRICTERRAGUMBOAMOURNODESDRIEDDUCATPAVESBRACTCORKS" +
        "CLOCKOUTGOSHOVEGIGUERIPENDAFFYMEALYCORGIHEMPYRESTS" +
        "MOUSESHYERLOUSEMUONSFLUBSYUMMYCOMERPARCHLIVENFAXER" +
        "GROPETHROBSPLITWIPESWADESTREWSPOXEDDEISTMESONBROMO" +
        "UNSAYRIBBYHOOCHNOBLYSTILECRAVESHIRTPAGEDROODSPOSTS" +
        "DUSKSSLAMSPROSEAWFULDERBYNIECESKITSDEGUMSCOREHYMNS" +
        "GOTHSALIVEPALLSPATHSFEEDSCORKYFONTSROACHHOKUMHOVER" +
        "MUSKSPLEINALGAEDICERVAUNTCROOKROOTYTOTERHOOPSSLUSH" +
        "SCUSEDUELSUNFEDCOIFSTOKERSIREDPROEMMAZEDCRIMPEYERS" +
        "GRIPSPUKESREIFYBUNDSSHIESSUMACRACESSAINTXOREDMASER" +
        "SEERSWHIRRKNOLLCZARSLUCREGONNASHRUGBLANDHOLEDCLUNK" +
        "VAGUEDYADSHONORCRONEUPENDDEFERLUBESMEALSDICKSPENAL" +
        "METREFACEDKIWISLAPSEJIBEDHATERUVULASEDUMTENDSLOBED" +
        "MELDSROBOTSILKYYOUNGMINASBUDGETEACHPLEASWINDSZEBRA" +
        "LATCHQUOTAGRAFTTILTHFORDSKITTYAGARSSLEWSBEFOGREFIX" +
        "MAVISHITCHLOGESLIMPSHOPESTHINKWORDYEASELWONKSSANDS" +
        "TWEETTOPESSLAYSSWEATRIVESKNACKBOWIESWARMPHIALTOGAS" +
        "CANDYNOBLESNEAKKEENSSINESQUIDSPIPESOUZELHEARTDRESS" +
        "KAPOKKHANSPULPYSTARETHEMEJUNKSBAKESRIMEDPECANBIFFY" +
        "TAKENFREERHYINGSTOKEGAPESIDLESGUILEGREBETWINSREBUT" +
        "SILTYRIGHTSNOOPRECTABOOTHDEWEDSAITHWHOREPACEDMATTE";
    public static final int COUNT = 250;
}


public class Words8 {
    public static final String W =
        "FLAMSSTAFFOILEDHYPESBEAKSSPLATHABITLOOKSPUKKAGOOFS" +
        "TUNESINFIXCLONEHERESPIKESTITHEEXEATKOINEMUCKSWASHY" +
        "PUTTSWISEDFATESMOLDSAHHHHGIFTSSHLEPBRACEBURRYTONIC" +
        "ILIUMFOUNTSODASJOKEDVISORMIXERPROVEDINESVITROLULAB" +
        "WINESALIENSNAREXENONDAILYFILARPRIORPLOPSFALLSGRIMY" +
        "SHEARGUSHYDARKYVIZORDECOYLOGICTESLAAGUESRAILSWHIST" +
        "YAWNYBARICTOYONBRIDEMOOEDRIMERBROKESHAREGLOOMWIELD" +
        "PLENACRABSRACEDOXEYEGIDDYTERSEROWANHEXADREMANBARMY" +
        "LIKEDCORMSOTHERFEUDSGENIIBRAINLEMURLOINSCHITSPINKS" +
        "SPARSPITONHILUMLOWEDGRANTHARMSDEIFYIRONYFACTSERUPT" +
        "FOLIAFILETWIZENPOLLYTUANSAEGISGAYLYTRASHRUGBYCLAVE" +
        "PARERKAYAKUMBERTRUERSLUMSHULLSMIREDBELLECEDEDPANIC" +
        "FADDYCLOGSDUPERFILMSLATHECARTETHERMPARENTHROEWHORL" +
        "STAINMINEDBORAXMANICMOMMYCREDOSTEELGRITSWISPSROVES" +
        "FLUMEWIDOWROBLEWACKOLIVIDHERBSMOONYSHEETCAROMREALM" +
        "CHILITERCEABETSFARADLUNCHVIXENFELTSBUTCHFINISREFRY" +
        "GIBESROVERSLOWSDINEDREDLYLOGINDINGOROASTSWAREPRESS" +
        "ROBESSAFESPOUNDJUDOSFERMILAPISRUNESCLOUDTALKYTOONS" +
        "RISERMUDDYSHARKGIRDSLITERDEEPSDILLYDULLYCLIMBFECAL" +
        "SAWEDSNOOTCELLOCLAMPKITEDMONTHHINGEDOPEYWHITSDEQUE" +
        "LUTESFRIEDFELLSCOSTATILERPUPASPROSYAREASGROWNHOARY" +
        "LUAUSPRONGCRAPSWHOASSCALPPOLERBLOOMTIERSNEIGHFUNKY" +
        "DENTSCOLDSMONKSASTROSHACKMAHUAIDLEREXISTTHREEABUSE" +
        "MILERSABRERAKEDHARPYUMPEDSTANDQUIFFIODICISLETSTUNT" +
        "MINORZONEDUMPTYOBEYSTHROWBACKSRETRYVEXEDOPALSNERDS";
    public static final int COUNT = 250;
}


public class Words9 {
    public static final String W =
        "BHANGWALLSGLUONMULCTCOYPUCHOMPSPIEDLOPEDFLIESGYVED" +
        "LIETHWAKESFAVORSHINSSWABSGAMERTRADEKOOKSSPERMRECTO" +
        "FORGEDADDYDOGIECARNYLOATHPETITPATESDEALSPRINTCENTO" +
        "UNCUTCOPSEJOWLYCUSPSCUTIENINESLUCIDDOGESGULCHGLOAT" +
        "LOLLSFURORHOERSPHONEDEMONKITHSGLUESLARDYTALLYUNSEX" +
        "TUFASTRIALCRAGSSUDSYCRUMBFORGOELBOWBOXESYULESALOFT" +
        "STONYHOBBYBRAVASHOUTGLUERDULSESHORESMARTRAJAHDITTO" +
        "VACUADRABSSTINGCYCLELACESBUBBABESETPATERMOCHAUSURP" +
        "CHUMPCLEATECLATLIMEYMOHELMIMSYLUCKYMORELCLAIMMATHS" +
        "DAZESSIGHTLAPELFORESCOMBSGROUPYAWNSACIDSFRANKPODGY" +
        "PAYEDVIVIDSULFAEPACTMETESGRIEFPIPEDCHARTQUOINHOURS" +
        "HOMESSIDESYOLKYSMITHSTAGSJERKYSCAMPBONERFURZEWROTH" +
        "HUMPSSWOONCADETCRASHSUPERYURTSFRANCFLASHCOCCIFAXES" +
        "SCONEBRAGSABOUTROWEDNYMPHPITHSOXIDEKNELLCOCOAIKONS" +
        "WISTSCORNYPILOTGREPSKITESIMPROHIVERCELEBTEARSFORMA" +
        "UNPEGHAZELQUAILWADISBLEATTORTETRAYSPEAKYTOFFSEASTS" +
        "LEARNBOBBYZOOMSPAGERCLINKSKIERNOVELWONKYSTATSSHOWY" +
        "SLURSSTEMSTILEDUNTILGUSTSWHELPTETRAGULESFAULTTHWAP" +
        "BLURTBEAMSTEMPTPEASEPUTTYSTOUTVITALEGRETSIDLESKUNK" +
        "YARNSNOSEYWEAVEKEFIRRECUTCHANTCOTESBREAMFLUNKTRUED" +
        "IVORYYELLAKIKESINANEFAXEDNURBSLAMEDOTTERERECTGRADE" +
        "BORERREADYRITZYMODEMBOOKSLIVEDPOPESGLARYLOCOSESSES" +
        "SALLYANVILPIMPSMOWERAPERSBEDEWPRODSDILLSRILEDLULUS" +
        "ANKHSBATHSUNFITCHAPSSEVERSATESSCHMOVIBESWOVENGHOTI" +
        "TEEMSTHEESANKLEMARKSGOADSGARDEFIRERWHACKPINTSLINTS";
    public static final int COUNT = 250;
}


public class Words10 {
    public static final String W =
        "DOWNYMUSTYFRESHFERALDIXITFEIGNMOLESLOGOSSKIRTDRAFT" +
        "BUOYSSPRUEWEEPSHOPPYBIKERSONAROGLESDEBARRAJASWATCH" +
        "VODKARILLEPLIESEASEDMANESRUCHECOPEDIMMIXSPREEBORNE" +
        "CHESTSHALLMANORARDORRUMBAWAKENSTEEPLIESTCONCHOUNCE" +
        "BRANSHOOKSWAFTSKNEESGRUELWHOSEAVIANTYPEDINFERLADEN" +
        "GAUDYLOXESMUJIKYERBAWRITEWENCHTECUMDICKYMIKEDSLAWS" +
        "JINGOWASPSGIANTDIMLYILEUMSABLEMESNEEDGESFINIFPLINK" +
        "FIRMSBLUNTGURUSELITEPLONKLUREDTEPEERUNGSTUPLEMELBA" +
        "CALLSOUTTAHILTSHASTEHALLSMODUSAORTAFINKSBANKSHASTY" +
        "HULLOLOSERNONNYLOTTOHUFFYJOINTVERBSVAMPSKOOKYOASES" +
        "ACNEDSLUTSDUMPYTITANFLUKEPOOCHBIGOTJOHNSLEPTAUKASE" +
        "VOILEKNELTKNISHPHONYMONEYWRIERTENETDOCKSBAIRNNARES" +
        "MILKSASANAMOISTFLAKYHATCHPENNYAXMANBONGOGINNYSELFS" +
        "BOLLSMULCHSCENEMARRYWASTETROMPPINEDNURSEDENIMGATOR" +
        "CAVILFUGITEXCELFUGALPOACHSPURNRANTSFAIRYSAGERBANES" +
        "HELIXSTOOPPOCKSSPIELHOMERWHICHSTAGEBRONXSLATELUBRA" +
        "PLIEDHEROSDOOMSVIERSCOATSFOXESYOYOSOLIVEOCCURFREES" +
        "PRAYSLOOKYLEGGYLIMBOCHUMSTRUSTBOLASTHIEFLILTSGREED" +
        "SELLSVANESCAMPOYOGASLIGHTMACEDLEACHRAZEDSLUNGBROOK" +
        "MYRRHLEASTSAVVYLIKESGARBSPOOEYFLOSSBIOMEFOSSEGRAND" +
        "WIVESCELLSNORMSFURLSATOMSBEAUTMULLSMOTIFDORMSKUDZU" +
        "HUMUSBETHSVENOMAMIDEGOFERETHERSIDEDYOKEDARROWLASTS" +
        "MEATSRHYMELIKERVIGILWARMSGOODSCLOMPRENALQUEENSHIKI" +
        "SHUTSFOILSPEAKSCRIEDSTEAMLATEXSPELTGALLSHOLESBURGS" +
        "NICADSLUGSCHIVETHIRDZEALSPETERPIGGYPETRIGREATPIGMY";
    public static final int COUNT = 250;
}


public class Words11 {
    public static final String W =
        "LACKSOPTICTHEREWEENYMITREACHESHEWERGHOSTPORTSWHEAL" +
        "FAILSNABLAPOOHSUNBOXPLUCKEVILSTITERBOSSASCOUTRAPED" +
        "EDITSDUMMYPAINSTAMESBATCHROWERGOETHCOMFYMAKESGUILD" +
        "UPSETGOINGYIPESDOTESSTUNKSHALTMILCHPAYEECOCKSBROIL" +
        "WALKSCANERPARSEWILESFLICSSNAPSWRYLYDOVESAPTLYCRUSH" +
        "EXALTYESESSEVENATOLLDEPOTBREWSCIRCARAISECANTOCROWD" +
        "PRIMEBEAUXSIZESARSONHICKSGAINSVITAESLICEFLOUTADORN" +
        "OWESTWELDSALDERTROWSZOOKSGENUSSUERSGLEBEBALDYDUKES" +
        "DOVEYLYRESSOLEDBOMBEFLICKROWDYBRANDPLAYSBODGEEMERY" +
        "WANTAULTRAARCEDSPAKEPILESYENTAINKEDJOISTBURSTTAILS" +
        "NODALSCABSSPEARRANGECARONUNITSFELONFIVESTRAITSHEER" +
        "SEXESSOLVESTORYPATCHNIGHTTUSKSSUAVEAXLEDBLEAKHORNS" +
        "WEFTSSPUTAOINKSGENREFLOGSWHEREDEGASBOUTSADDERFRIES" +
        "ACHOOSPUEDAXIOMREBOXGILTSTREYSMULESTITREBELAYCRUMP" +
        "BALDSWETLYBIGHTKINKYNOSESREPLYSWORNCROAKMOANSJOEYS" +
        "LOCKSPESOSBRAYSSTAPHSONNYBITERELANDAGREEMAKERSHAME" +
        "GABBYDARERSCUDOBEFITMIXUPGOLEMVESTSMIXESFEELSBEDIM" +
        "GIMPYASSETPOLLSOUGHTHOGANPRIEDQUAISFAWNYACINGPRISM" +
        "COUPSBOOTSGOOKYCROWSPICASCURIASLUNKMUMBORATERWHIRS" +
        "STALKFUNNYTEALSCLANSDIAZOHYDROAMAHSRIFERMENDSORBED" +
        "RISENNEWTSBEBOPGOOSEBAKEDPSYCHSTRAYSPARESTARKACUTE" +
        "IXNAYKELPSJENNYTOTEMVOLTSCHEWSANGLETOPERADAGEUNBAN" +
        "FRILLCHALKALACKPUPALFEMURENEMYBUSESKNOBSMUFTITRACE" +
        "SPOUTJEANSWEBBYTHANXFELLAPULPSPURTYPEATYHUNTSSOAKS" +
        "RENTSSHISHBASILFILTHPEKOESNAKEVOXELWANEDSABERMISSY";
    public static final int COUNT = 250;
}


public class Words12 {
    public static final String W =
        "ROTORCRUSTBROOMMASTSFOLKSSIXTYBELTSELECTPRANKGORSE" +
        "FEASTBASSOBURNSCLASSLIRASRATTYTZARSSARANTRAINYOGIS" +
        "GIVENDEITYBOARSWISPYOUSELHOBOSLEGALCAREDSILTSDAISY" +
        "GRIMESEGUEDIRTYNOMADSTORKWORLDBONEDBROADTAMEDDROSS" +
        "PAWNSCLUNGSURDSSUGARBITESBOGEYANTEDLINERJOULECHESS" +
        "FINNYTENSESHARPPANSYBETELSNEERGUILTCALYXSIBYLTALON" +
        "BILLSTENTSJETTYBUFFOTINGSFONDUFINERMIDISLATERDRIVE" +
        "REDUXOINKYRAKESMAMMYTINTSVIPERPROUDRIVEDTUBBYCLOAK" +
        "ATLASPOCKYWURSTMETEDBLUEDAURALTAFFYASTIRAQUASCLACK" +
        "BOOBSVIOLSFLACKOUIJAWHAMSDARKSMODELPASTARANKSVIOLA" +
        "ENTRYDOSERACHEDSLEEPPICKSAMITYAGAPEGUTTYBRASHLUMPY" +
        "HAYERSADLYGRODYDUTCHHIRESVOTESVIALSGLORYSUETYWIDTH" +
        "DRUMSGRIPEPROWSTERRYPHOTOLEVELNEWELPLASHHIVEDSOPPY" +
        "KARMASHINEODORSPOSITHURLYCEDESMAJORQUAKECHURLSTRUM" +
        "SPANSDEUCECOLORSTOUPTIGERRUMENPRYERRANDSCRUDEWORKS" +
        "BAIZEFINCHILEUSSMOTESHOOKHELMSTWICENICHEWASPYABODE" +
        "APNEATALUSMESASBLUFFTATTYGAUZEHOPEDEXPOSTUSKYCOEDS" +
        "LOOPYMAXIMMADAMGRACETRACTPOLEDBOOSTCEDARPANESALLOT" +
        "SORTAGNAWSSTIFFSWINESIZEDVENTSPUNKSFLIEDCORPSHUFFS" +
        "JINGSWRECKDUDESFENCEAPHIDTHAWSPISMOTILDEVIDEOBLACK" +
        "BUSHYABEAMPURGEPROWLCONEYEXTOLQUASHSTOOLTRIOSHALLO" +
        "ADLIBSORRYSLILYSTARSAWAREBULGEASCOTCANNAUNDERMYTHS" +
        "MIDSTGIVERSPINSTEMPILAMBSSWOREKNURLSHEAFGLUEYREINS" +
        "LAPINFICHELOBARBUTTSHUMORPASHADRAGSUNMETAMBERDINER" +
        "LAMPSPERDUFROGSAGATEOWETHZOMBIFLUTECHARDRADARCRANE";
    public static final int COUNT = 250;
}


public class Words13 {
    public static final String W =
        "AMIGODOYENNATCHCREWSBISONMEMOSAMPLYTROTSCASTETOTED" +
        "MATESDUPLEDECKSGLOWSPOUFSLOFTSKLUGEWAISTSPICYBANGS" +
        "ERREDSTIESTESTSULCERMUCUSDILDOKIVASABENDPREYSTUMOR" +
        "GRINSTRAMSEIDERCHOOSAIRERDEALTDEATHFETEDEMIRSRIVET" +
        "SEAMYGAFFEHUGERDOZESPRIESTRUCKHUMANNAVALABLERSURGE" +
        "DEVILFLAPSLURIDLOOSEFOGEYSLUEDWHEWSSTINTGOOSYSOFTY" +
        "HERDSSTEEDPHASEYECCHMAFIAMOOSEFAMESBRUSHFANNYADMIX" +
        "DOFFSARRAYLOCHSRELETTEDDYWHOMPSUINGHENRYEDIFYTRAIL" +
        "TOYEDGOALSBUSTSTOMESBOGIEPOLKANULLSFROWNRONDODOLLY" +
        "DASHYINAPTLAGERCHECKHURLSSMURFCREAKHONESSNOWYAPACE" +
        "SCOPEARBORARIASGLENSTUBASSCIONHUSSYCRAWLBUXOMPSSST" +
        "UNPINALLAYTAUNTLOTTABOTCHBOFFSDUCKSHEELSCHATSVIVRE" +
        "FIRMAUNMAPELANSJUNTAPLEBSMIMERNAMESSCOURSAVORQUITE" +
        "LIERSFAWNSOVERTHOMMEIRATECABINMAINSBENTSBALMSBEGOT" +
        "BRADSARMORBEATSCHERTLISTSMILLSIDYLLHELPSHOLDSPSALM" +
        "EJECTSMIRKDELISAILEDDRYERCRYPTGUNKSBELLITHUNKWACKY" +
        "SUSHIYODELCARPSALTERMOULDTWITSMAUVESWATHTERNSDITCH" +
        "OCEANLIFTSCARVEYOKESMUGGYRAZESCOVETWANESAWAYSOOZED" +
        "CRIMESLINGSORERSOLIDOFFEDBODESRAZORMOTORFAREDJIVES" +
        "PAVANWAVERWENDSRECAPMURKSYOWLSGUYEDLENDSTANGYFOIST" +
        "WORMSHIPPOSHELLALLEYNERDYCATCHDRAMAALEPHAURASCHORD" +
        "DUPEDIDIOTDIVVYTAKERGOUGEGROKSWHIRLDUCTSSHIMSHIKES" +
        "WAKERWHINYDRILLTOURSAWOKEREEKYHUTCHKNAVECLEARHENGE" +
        "SAVERVEALSJESTSGRAMSZINGYGUMMYCOINSSHIRRFLECKINSET" +
        "MISTYPATIOVINYLRABBIHODADALERTFADERRIALSAVASTVELDS";
    public static final int COUNT = 250;
}


public class Words14 {
    public static final String W =
        "EPOXYSWAYSSLOTSUSHERACTORPACTSTIREDSLOOPDAMNSMANGY" +
        "PRONEARRASWOOLYTHORNHIRERZESTYPANTYRUNTSDACHAOVERS" +
        "BITSYOAKENMOTHSLICKSMIDDYSINGEATONEMAMASFLAILBEZEL" +
        "MUFFSPADREAMUCKBLOBSWILEDSHITSVILLACASASORDERSHOJI" +
        "SCORNHIDERLEGGOSWORDTOVESSPILTFOOTSSCARFRIDERNARDS" +
        "BUMPYKNOWSJACKSFINALCLOPSHEWEDJUMPYCEILSPLAINHAUTE" +
        "SPITZRADIOBRUITNINJAHOLERALLOWAXMENCORESLINENGOLDS" +
        "PEALSJOLTSTECHYSARISSLUESWHIPSCOYLYSPUNKSTYLEDUSTY" +
        "WEDGEGIROSCLUCKCOALSFOSSAGENETGLANDWINEYNIMBILITHO" +
        "CURLYREDIDTSARSTOTALCAGERHOSTSCULLSVILERSTILTMANNA" +
        "EXURBJINNSRAPESFLORATRESSMINISSCREWSMELTOKRASFIXES" +
        "MORESFOAMYRECURCABALFINEDSNITSSIFTSMAPLESWEDENIXES" +
        "RAYEDMIRTHFITLYBLASTTHINGDROPSRHEASSTIRSHOLEYPAYER" +
        "DRIERDOZEDINFRARANGYDECALGAMICTOTTYCOYERZLOTYDAMES" +
        "FRIERDREARLIBELVOIDSPEWEESTUDSNOONSEMOTEBWANABODED" +
        "RIVALWINDYMOULTSCATSVELARBEGETVOMITFLANKLANAIVALID" +
        "JERKSCAGEYABAFTPSHAWEBBEDPUPAEWRACKTANSYALIASBIMBO" +
        "THRUMWHARFDRINKTIPSYMOLTSTIDALAGORARIFTSPIXELFIXIT" +
        "VERVESPUDSCOCOSSISSYRUDERRANCHNEWERREELSCHILLOBEAH" +
        "PLAIDLIVERLAVESFIXERSHUNTROUGHBEIGEDOZENSPURSWIFEY" +
        "WIRERNOTERBAZARGOURDPUBICVEILSDROVEPLUNKMITTSBOSON" +
        "WEARSSPOOKAUGURLOSESKENAFMIKESTRUMPOFTENNOTCHBALLY" +
        "BRINEOMBREQUOTHNARCSLEADSWARDSMERRYSPOONBATIKMEADS" +
        "FUNKSCUBITSONICGENTSWAGESBELLSMINIMGAMINSALONAITCH" +
        "PALMSHULKSDIRERVOICEMONTESPELLPITCHCOUGHALGINCURLS";
    public static final int COUNT = 250;
}


public class Words15 {
    public static final String W =
        "EGADSPRAWNWEEKSPFFFTTUCKSCHOCKTRIMSRAVENHONEDNASTY" +
        "GUESSSPITSVEINSTURNSIVIESRUNNYDETERHACKSFAIREVANED" +
        "DROOPFACERTURDSCOLTSRATIOCHAFFHIDESBLEEDMASSEALOES" +
        "THUDSCLEFSMECUMWEIGHRADIIINDEXPETTYSMITEWAZOONUDIE" +
        "JEWELSYLPHLOUTSCOOKYDIKEDPENCENUDGEFOVEADWARFINODE" +
        "TELEXREAMSTRANSPRIERDRECKRICEDPINKYWAGEDAERIEUMBEL" +
        "HOUNDGALASPLATEGONADPINUPPALSYSPUMYOLEOSOMENSNITRO" +
        "ROUSELIEGEWORDSCITEDTRICKWILLSBONNYABASHHIGHSTHINE" +
        "RANDYSUPESBIGGYSHELFBRANTALKYLSPAZZSHUTEREMITSNARL" +
        "BASERFIXEDFEARSFRAMEFORTSWITCHGULAGYIKESEXUDETINGE" +
        "SLIPSAARGHDEBITNEEDYSWASHWAGERJEERSGATEDBLESTSPAYS" +
        "SETUPMENUSORCASOBESEMOLALPAREDGAFFSSLEDSCOULDPASSE" +
        "BRIERDUNKSCREEDSEMISBURETTALKSPALMYFLAWSKRONEDRYAD" +
        "EAGERBASISWOOSHTUBESBEANOABACADJINNARUMSSLIDEBLANK" +
        "AXONSGOYIMBOORSSOLARGLADESTUCKLIONSTABBYCREPTWEEPY" +
        "SNAFUCLUESSPILLGIMMEAUNTSBATHEXYLEMPROFSTRILLMACAW" +
        "UNDUECORALFUMERELDERBLOODICERSDOGMACLUMPCOSTSWONTS" +
        "FLAREGUNKYSEEDSPOISEURINELOYALREVETGRAINPALERBLEND" +
        "FLUESSLEPTGREENSPITEBATEDANIMAPIONSLAIRDSILOSTRUSS" +
        "CLOWNCAPONFUSTYSCUMSPARDSGRAVEMEATYSCUBALEDGEMAIZE" +
        "JOWLSFUELSYOKELAGONEOCTETIMPELSKIFFNEATOBROWSLIENS" +
        "NANNYVISITCUPPYBEETSFADESCOUTHESTOPSPIESALTOSTREAP" +
        "ACNESGUPPYNOIREMOVIEDITTYAGINGKILTYALUMSPLEBEPLANT" +
        "BALKSMAZESWOOEDSWINGFORUMCOCKYANNUMTHUMPCUTUPGUSTO" +
        "GOUTYFOLICGALESTORUSJUICYTILESDRUBSBULLSADZESTOFFY";
    public static final int COUNT = 250;
}


public class Words16 {
    public static final String W =
        "KEBOBROVEDTACKYBARESLULLSPASTSAGAINJIFFYABYSSKINKS" +
        "SHOERWIPEDSEEKSENEMAPUPILSWANKLOANSTHUMBJOYEDBEECH" +
        "BYRESPATTYNOWAYFIVERPIPETWRYERPUREEAIDEDBRINGTROVE" +
        "URBANERUCTBLITZDIMEROFFERNONESRISKSQUAYSSINUSQUILL" +
        "BUSBYTRYSTPARTSSHAPEPELTSAPRONSCURFRULEDSULLYTIMID" +
        "CUMINDRAWLDULLSVISASJUICEDWELLWEALSBERMSBOWELCHIPS" +
        "SEDERBASINFOWLSSOLESKEYERVENDSZESTSPRIZEPEARSPLAYA" +
        "PANDADIVESHOWLSDRYLYPEONYLAYUPHUMPHAWAKERIDESGAPED" +
        "GRUBSBIFFSBURRSROARSREBIDBUNCOSPOOLCLERKHAMZASNIPE" +
        "SLASHGLASSMUMPSAWARDSERGERHEUMMYLARCAGEDFETESACKED" +
        "SAUTEHUMIDASPICPARASLAKESNUTSYKAPUTHOMOSTRUNKENDUE" +
        "RUMPSBETASYAWPSPOKEYOPENSCOOPSMOUNTSPIKETHANESCOWS" +
        "AROSENIHILMEBBEQUASICROFTBAULKURGEDBOOMYCURDYNIFTY" +
        "KNEADDELTASUETSMAVENTROOPPUSHYABHORPLUSHGOWNSTENON" +
        "COLASHOOTSOPINEADMITLANDSTWEAKFLOPSAZUREMOATSWORSE" +
        "BOWERCHIFFJAKESSOAPYSALESCRASSTIBIADOWERJADESSAGAS" +
        "DATESCEDERFUNDSGLANSTOADSFRIZZTHESETHOSELATINOBITS" +
        "GRADSGRASSABOVETOQUELOADSBURPSPULSECUBESFORCEANNEX" +
        "DUNESSONGSTIMESSTUBSPRAMSFLUFFDINTSOOZESCLAWSCONDO" +
        "BOOBYCOLONHOVELCAMELOPIUMTITLESTABSARGOTTOPAZCLEAN" +
        "PATSYMEWEDJUMPSTARESTORICLAXLYSOFASSNOTSPRICESPICE" +
        "RESAYSHOOSCOWEDAMPLETARDYTWINYMORALFEINTTOPICHEMPS" +
        "GLAREFLOODBORESHAULSUTERIFAZESMUNGSLIVREROPEDSUMPS" +
        "ARGUEMOLLSTUNEDSITEDCALIXSNUFFLUNESFABLEMORPHBOSSY" +
        "SYNCSIVIEDVALESWRONGPOURSGIPSYBALLSARSESRAMPSLINTY";
    public static final int COUNT = 250;
}


public class Words17 {
    public static final String W =
        "CLOVELEMMELOVERSHAKYHOPEROUTDORUMMYWAXERDIDOTMUTES" +
        "LUMENTONALPIECENEWSYMARGEPANGASHAHSDRIESBLARECHAIR" +
        "LOONSFILLSSIXTHMUSERSLACKELVESSUCKSPIINGWHEEENOTES" +
        "DICUTMETALBULKYMOOLADONEEOLDIEINCURGAZEREARTHVILLE" +
        "WHIPTLONGSKYRIETENTHCUINGMORTSCANTSWOLDSPARRYHAMES" +
        "INPUTSWIFTDIVEDROOMYSTOPSCASESSAUCYSUPRAJIMMYSEPAL" +
        "SAGESDODOSBEADSCIVICROOKYPINESHEARSREPELPENGOMAZER" +
        "ROUTEENDEDBLINITRUCEWORRYWIMPYSOWERTWATSCASKSPIQUE" +
        "FISTYMAIDSLIMEDSEPTACHICKBROODBAHTSSILLYPAUSEBLOCK" +
        "CAKESEVERYUNSETREADSMOPERBABELCLANGEAVESSCALEOGRES" +
        "INLETBUILTQUALSLATHSHOLONDREGSSNARFSNOODPERKSEMBED" +
        "OGLEDNESTSSCAREDUCESVITAMTABUSDIARYQUARKSTUNGFLESH" +
        "LOOMSTYRESPOINTDUALSSTREPFLUKYBEERYFOLLYVERSTKIDDO" +
        "MADLYSCUZZGLEANSTINKTHICKEVICTAPPLYDUNGSADOREDROWN" +
        "OLDENSPOTSRHINOCUBERWOOFSLEASEZINCSDAVITANNASSHADS" +
        "KINGSPEARLDEBTSGUTTAOAKUMPIETYBOSUNWHEYSITEMSCLOTS" +
        "PRUTAORATEPENISBRENTRIDGEGUARDRUDDYFRISKHOOEYBARKY" +
        "SPRIGSURASGEARSJULEPHEISTGOUDAEXAMSMARSHOUSTSTOWED" +
        "STUFFPAEANSEINEPEENSGRAILGANEFPOOLSABACKVISEDURGER" +
        "CAUSEGORESSQUADCALKSGODLYTODDYTABOOHERTZGROVEBONUS" +
        "MEETSCUTERDISCSUNAPTMOOCHAROMAPOSESDURSTSHMOOEXPAT" +
        "PRATEEERIEBABESCOMBOFOODSBIBLEREACHINTRASERVEINKER" +
        "SNORECRIESSKOALJAGGYRUSSEFRUMPTROTHBRACKANGRYCOTTA" +
        "FILEDSPENDUNSEWSNIPSBLIPSTAXESEPSOMHARESHALMAAHOYS" +
        "COONSDONNAIMBEDSHEIKMUCKYYACHTSTEAKDYNESNERFSSLYLY";
    public static final int COUNT = 250;
}


public class Words18 {
    public static final String W =
        "LUTEDJAMMYWORMYHANKSDOWNSMUSTAWAXEDWHILECOOCHPUMPS" +
        "THONGSITUSFLITSDUCALZOOEYYAHOOGROWSFEVERSKIMPABBEY" +
        "GOLLYEQUIPMOTESTALESSLAINRUMORHAVENHARSHTUNERSEATS" +
        "ARENAONSETCURVYADDEDWHELKALBUMCHEEKMOODSRAIDSGENIE" +
        "GUNNYETHOSICILYFANGSVAULTPLATSWOWEDHANDYNUTTYBOOZE" +
        "GRAPYOKAPICRATEBOSOMFARESPHLOXCRAZEMOUSYCHUGSCHEEP" +
        "EGGERROILSNATALWINOSMUSHYCODERRUSTSALOUDENDOWSOAPS" +
        "CIDERHIVESHEDGENADIRWIPERFREEDTOMBSTEETHRESETSLINK" +
        "DIGITSTALEGRIDSFLINTOATHSEAREDFIRTHSNAKYAPARTWEIRD" +
        "RESINSEEDYHUNCHSHOTSSTOLEETHYLFUZEDPALESFATWAREBAR" +
        "CURSEPACESPARKSWORTHAVAILLITHEPOSEDSTILLTUTTICYCAD" +
        "SNIDESPLAYWORSTPEACHSNOOKWOMBSSOBERBRIBECHURNWILDS" +
        "RUTTYROMPSONCETBAYEDRAKERSWARTTUFTYPEELSBRUTEGIBER" +
        "LUXESNITERCOVENFUSESAFOULINLAYBLAZEUNIONOOMPHSURLY" +
        "STOATSOUSEVERSALIPPYHUNKSREVUEQUEUEHEXESBRIEFNATES" +
        "SHOESLUSTSGLEAMLIGNESTORMMEANSMULEYKEEPSANTICMIRES" +
        "CURERWIMPSDOLORDUSKYSCOOTHEATHEPEESCURDSCRITSSISAL" +
        "SLEETAHEADLAZEDDOUGHSWAPSRIDGYDOMEDUNTIEFIRSTFILMY" +
        "FLAKSMURALPANGSHINTSTICKSCONESSTAKEHAWEDPLAITFIFTH" +
        "MOURNADMENBRUSKTRIPEMITESAPSESVAPESPOKERBOXEDSMEAR" +
        "DARTSCLODSVALORORALSSHEDSZOWIEMONDOLOESSCROWNPAPAL" +
        "HOARSTOTESSCUFFSULKSFILLYGOREDCHINKREUSEDANDYMACER" +
        "MITERDOLESTRICEPUFFSROUGEEBONYTWINEFLEESMUCHOHASPS" +
        "ASTERBENCHGYVESCHEATCRAWSGOOEYARMEDBREAKWELLSEVADE" +
        "BERETORINGBIPODBITCHUDDERRUINSHOWDYGAOLSICIERTEMPS";
    public static final int COUNT = 250;
}


public class Words19 {
    public static final String W =
        "WOOLSWOKENDOWRYMANTADOLCEAXINGDEICESEDGYGENESWOMAN" +
        "LINEDBRAWLRACERNONCEUSERSSMILECAMPSBOARDMAGNABONKS" +
        "SALADICHORCAMPYSPIFFPEERSYOUSEAPPLEGAPERGIBEDACORN" +
        "REIGNTINNYCHUNKCORDYBLOWYRESEWFLOATWEDGYSKULLBOAST" +
        "LILTYMUSTSFUMESTRIESABASELITESALLOYFUMEDMOPEDKLUTZ" +
        "HEXERTEENYRAINSDICEYDEMURLINKSKNOUTGUTSYJAZZYALPHA" +
        "EVENSPORCHBEERSTOUTSSACKSDOTTYLORRYSMACKBASTEBAWDY" +
        "HEADYSKIESALIKESWOOPJEEPSFAINTABLEDMERGESOLOSCODED" +
        "NINNYFIFESCOREDBOCKSCRACKLOAMYWOOZYMEDICAMAZEEDEMA" +
        "TAROTFROTHFIBREMIMEOFAGOTHANGSJADEDGYPPYPOOPSEVOKE" +
        "FUNGOBOUGHGAMMACONKSMOTTOWRINGWIDERPAPPYPOPPYSWEAR" +
        "NINTHSTYESUSAGEBOGUSWHINEVIRESPRIDEBEAKYCRAMSFOURS" +
        "POLARSEEMSRENDSWEBERHOLLYSOOTSCOMETSTEALWAGONTRIKE" +
        "PLOTSBREVESUITEBRASSHEREMFIZZYJINKSWOULDLADESGAWKS" +
        "TIMERFROSTSEBUMMANGEALOOFBRIGSDONORJOINSZONKSFLIER" +
        "CLOSECAROLOATENWAIVESHANKMAULSEIGHTPROXYHALTSPOLOS" +
        "RAINYBUGLECOVESVALETCLAMSTRIADCOUCHSUNUPHALESCARGO" +
        "SHIPSPLUGSDIPPYVINEDSATEDTEMPODUFFSMOLASCABBYSHAMS" +
        "GLEESGHOULGRONKSUTRACROSSSTOMPSPADECUPPADISCOLAYER" +
        "AIOLIAMONGLUMPSMERCYWELCHJOCKSCABLEROOTSSLIMSTAMPS" +
        "MAMBOSANERSLANTTREESBINDSZONALDRAWNGAZEDARTSYLANES" +
        "CONICWAILSAPIANICONSUSINGMORONBOOZYSTRAWCHASMCOUPE" +
        "DEADSSPECSANTSYVICAREGGEDSLOPSSHAWLBOXERSNOBSDELFT" +
        "QUIPSAXELSPAWKYBUNKSODDLYROUTSUNRIGLAWZYNAMERSPARK" +
        "STREWCASTSORLONLICITPAWERJAPANTONEDDEEMSINDIEFORKS";
    public static final int COUNT = 250;
}


public class Words20 {
    public static final String W =
        "OKAYSSTAMPBARFSZINGSCLICKCATEROFFENDECORLIARSLOOPS" +
        "CRESTGAITSSEIZEGRAVYSCARSANILETHEWSINTROJOLLYSTRUT" +
        "LAVERVINCABUNTSPONESTULLEFETORASHENTHINSSLURPPAVED" +
        "CAPERGAMEYBARKSTWILLLINGOTIDEDMARESCUPIDSOCKSOWNER" +
        "COVERTILTSGOLFSSWIVEWEANSPACKSWASSAEPOCHSLANGEYRIE" +
        "SHIERJUMBOSAVESFRATSRISESGAYERFLOCKCARPYCLEWSHOODS" +
        "PLODSDIVOTCHAOSDEFUNDOGGOANGSTCOLICKEBABCREELJIBER" +
        "LEAFSOGLEREAGLERALLYFORAYSTOREMEDALWAXESYARDSVACUO" +
        "BRIESAPHISKILOSHAUNTRATESMIMEDLOPESTHEIRBERTHWHOPS" +
        "DAWNSMIMICTEAKSROCKSBUFFSCHOPSGROINDROOLCHINOFECES" +
        "BOATSFATSOPRESTHIKEDSIRESTATERSIGNSBRICKCODONDELVE" +
        "SHAVEDUVETWINCHDOWELCIVILFIENDSCADSRAGESLIMESBIDES" +
        "CACHEPASTYBLADEJOKERSKINSLEECHSHEENDRAKEBARBSASPEN" +
        "LEAPTHILLSEXACTTABLETEXASHEAVYFUDGESHALEETHICSPOOF" +
        "NAMEDSERIFSHORTBIPEDBUENOCRANKFERNYREBELWEARYFUSED" +
        "UPPEDDICOTSMOKEDRAYSPAWEDSLOMOTYPALDRONEPAILSCURED" +
        "DIDOSHEALSINEPTEYINGSIZERETUDEEXTRACADDYBLISSGNASH" +
        "ORBITFAERYMOWEDANNULDEMITMUSICGRILLICINGBEBUGANTIS" +
        "ODIUMGNARLTANGODIALSTOUGHLURERSEMENFLAGSSTEPSFATTY" +
        "SCHWAVEGANFIREDPIXIEBAITSDROIDADIOSCAWEDSOOTHBIGLY" +
        "SWIPEBEGUNSNORTOLIOSSTROPTAINTPENESOCTALCHIDEPILAF" +
        "SNOUTLAMASAIDERMRADSWAVEDFROCKPARTYWRESTEMPTYPILLS" +
        "WEESTRULESSWARFREDOXSPUMEMACROBESTSSPIERPUFFYSMUTS" +
        "NAPPYSTEWSGYROSDUPESFORTYGROANIMAGOBYTESWHIFFABORT" +
        "BLOTSLEVISSPICSSPATSBOOKYINURERESAWSHONECHUCKAMASS";
    public static final int COUNT = 250;
}


public class Words21 {
    public static final String W =
        "WANTSTUBERTEARYLABORMASONPERCHINGOTBLOATUREASLEAKS" +
        "WOWEENOISYINNERIDOLSUSURYPOUTSTENORLAMESBOREDTAPIS" +
        "CALMSEARNSPACERBANNSRILLSCOOTSATTARROUSTFRIARGIRLS" +
        "DIETHWATERKLUGYFIELDDOTEDLUCKSDUCHYIKATSTOYERMIFFS" +
        "PIKERLAVASDWEEBHAPLYPROMOBUTTECURIOCHILEANIONPANTS" +
        "FTPEDMILESDOXIEGISMOJOUSTFIATSSLYERSAMBALOPPYCHEWY" +
        "HORSYJIHADDIRTSPYRESMAYBEMOLLYJUNKYTHEFTBRISKSTALL" +
        "DEEDSWHENSHATEDWAVESSCOFFMALTYSPASMESSAYBOMBSFEATS" +
        "QUILTCHAWSHERONWAKEDLYNCHSCRIPDODGECRONYBANJOGIZMO" +
        "HADESAQUAEIGLOODRIPSGILLSAMBLEUNZIPGOONYEMAILTHATS" +
        "SALSARAVELHAIRSYELLSACTINLAVEDHAZESFACTOMOOTSPEEPS" +
        "RAYONRAPERWHISKCOURTESTERREHABPRIMACHOIRPERKYANGEL" +
        "MOSEYDOPESEKINGTARNSAXIALFOCUSUNIFYSHADYGAUZYCASUS" +
        "SLOBSSTEADBESOTMINESSIEVECREAMYIELDMONADAIMERZILCH" +
        "NICERDEFOGWOMENKELLYPLUMPPUNTSLEAFYLIFERQUERYTRAPS" +
        "QUALMRABIDPIETATIFFSGASPSCORNSTRITESCRAPVAPOROZONE" +
        "YOURNCOXEDREARMWALEDSHINYBIKESADOPTVISESBLURSMOMMA" +
        "MAGICTHIGHBHOYSAIREDMUMMYSINGSBIERSBURLYCANONNUKES" +
        "SIREENARCOBOCCIABBOTCHINSNOHOWSASSYDALLYADEPTFLATS" +
        "WHIZZBOOMSPROBEKNOTSBALKYBIRCHAPORTDAZEDCORDSSPORE" +
        "TOPOISPOKEABATESYRUPROSESPASTEPLUMSSWUNGCANNYUNITY" +
        "ALIGNRINKSBASESDRILYIDLEDEMCEEOVULEBLASHPUNCHSHAKE" +
        "LAUGHSHUSHBIDERERRORBUSKSPINKODATUMSECTSBERGSHOCUS" +
        "TWERPYOUTHCAMEOSTELETOXINTOKEDSTASHHAILSOODLESCENT" +
        "SIEGEGASSYGREYSSTOICNEEDSHYMENABIDEPLAZAQUELLVULVA";
    public static final int COUNT = 250;
}


public class Words22 {
    public static final String W =
        "MUTERNEONSEPHODSOLUMTOILESPANGSQUATTULIPGEESEGIRLY" +
        "SIRENJOKESPANEDHAVESPRIMSVOCABRELICHOAGYYORESPLUME" +
        "DIDSTFOGGYSAXESKAYOSBELOWDEISMKICKSBUILDCOMICSTOOD" +
        "TAWNYMEANTSLEEKTUNASDUETSSWEPTFOLKYGROUTFLASKFLEAS" +
        "MIAOWHAPAXSTOMATAKESGAGESPIVOTREEVEPORKSWITHSSEARS" +
        "PARKALOVEDSPORTTERMSAMENDCRIERGROGSSLAGSOWLETZONES" +
        "LIBRAPATENGLAZETIGHTPOWERFIRESIMAMSGOTTAKNEELPERIL" +
        "RUBESSYNCHMEMESTAXEDSOUTHCRAMPMEOWSVAGUSMUSEDHUBBA" +
        "RIFLETILLSFEWERRUPEECHARSHUSKSTUTUSREAPSPOKEDCOBRA" +
        "TIMEDDOMESAMINETYINGFULLSGAPPYUTEROARISEFENDSGRIST" +
        "SYNODYANKSWAFERAVANTWHALEAVERTVITASPANELQUIREPOKES" +
        "MINKSSKILLKOALAOHHHHWIREDNOUNSDARESFOYERSTICKNICKS" +
        "WHOOPMINTSBITTYMEANYKILLSTAPEDNERVEGLINTSOCKOOCHER" +
        "ENACTFANINLUNGEMOSTSDUNNOSEESTNACHOSLAKEBRAIDGRUNT" +
        "RAWLYDYERSTESTYSMOKYASHESDAUNTTUBALPYLONGUISEFRAIL" +
        "ETEXTLIMBYTOMMYQUINTMANSEPOSSESNUGSHALERHONKSZETAS" +
        "PLEADALGALGLITZQUADSJIVEDUNATEMOSSYDICTUFLAYSKAIAK" +
        "STAGYSKYEDAUTOSTOLLSKIRKSBINGEQUIRTRAWERMACHOAGONY" +
        "SITARCHILDWHANGLAITYDOZERTAMERCREEKNEGRODORKSSQUAW" +
        "JUNCOHENCESABRAGULLSCUSPYTWIRPPEDALDINARTURFSDINKY" +
        "NODDYTORSOFUZZYBLOWNLIKENDEANSHOMEYSHOWSTRUTHTURPS" +
        "ADOBEGOATSDARNSFUSSYGULFSBLATSWAHOOEDGEDFUCKSTROUT" +
        "BUNCHBEARSATTICQUIRKMAXISPEONSTACITTHENSSQUIBCHUTE" +
        "KEPISRURALGRATEDICTABAREDCIRRIDICESGORGEWRENSSITES" +
        "KRONADEMOSCHEAPDALESCUBEDROOKSRAVEDNEXUSMELONWRIST";
    public static final int COUNT = 250;
}


public class Words23 {
    public static final String W =
        "PAWLSHADDAGESSOSLOGSGREETTOILSBAILS";
    public static final int COUNT = 7;
}

    private static final int MAX_GUESSES = 6;
    private static final int WORD_LENGTH = 5;
    // total number of words across all word chunks (including Words0)
    private static final int WORDS_LENGTH = Words0.COUNT + Words1.COUNT + Words2.COUNT + Words3.COUNT + Words4.COUNT + Words5.COUNT +
                                     Words6.COUNT + Words7.COUNT + Words8.COUNT + Words9.COUNT +
                                     Words10.COUNT + Words11.COUNT + Words12.COUNT + Words13.COUNT +
                                     Words14.COUNT + Words15.COUNT + Words16.COUNT + Words17.COUNT +
                                     Words18.COUNT + Words19.COUNT + Words20.COUNT + Words21.COUNT +
                                     Words22.COUNT + Words23.COUNT;

    // --- Colors ---
    private static final int COLOR_BG      = 0x121213; // dark background
    private static final int COLOR_EMPTY   = 0x3A3A3C; // empty tile
    private static final int COLOR_GREEN   = 0x538D4E; // correct letter
    private static final int COLOR_YELLOW  = 0xB59F3B; // wrong position
    private static final int COLOR_GRAY    = 0x3A3A3C; // not in word
    private static final int COLOR_TEXT    = 0xFFFFFF; // white text
    private static final int COLOR_CURSOR  = 0x565758; // current row highlight
    private static final int COLOR_WIN     = 0x538D4E;
    private static final int COLOR_LOSE    = 0xFF4444;

    // --- State ---
    private String targetWord;
    private String[] guesses    = new String[MAX_GUESSES];
    private char[][] hintColors = new char[MAX_GUESSES][WORD_LENGTH]; // G Y X
    private int      guessCount = 0;
    private boolean  gameOver   = false;
    private boolean  won        = false;

    // --- UI ---
    private Wordle      midlet;
    private WordleCanvas canvas;
    private TextBox     inputBox;

    // --- Commands ---
    private Command cmdGuess;
    private Command cmdNew;
    private Command cmdQuit;
    private Command cmdOk;
    private Command cmdBack;

    private java.util.Random rng = new java.util.Random();

    public WordleGame(Wordle midlet) {
        this.midlet = midlet;
        canvas = new WordleCanvas();
        newGame();
    }

private String pickWord(int id) {
    int absId = Math.abs(id);
    int chunk = absId % 24; // there are 24 WordsN classes (0–23)
    int idx   = absId;

    switch (chunk) {
        case 0:  return Words0.W.substring( (idx % Words0.COUNT)  * 5, (idx % Words0.COUNT  + 1) * 5);
        case 1:  return Words1.W.substring( (idx % Words1.COUNT)  * 5, (idx % Words1.COUNT  + 1) * 5);
        case 2:  return Words2.W.substring( (idx % Words2.COUNT)  * 5, (idx % Words2.COUNT  + 1) * 5);
        case 3:  return Words3.W.substring( (idx % Words3.COUNT)  * 5, (idx % Words3.COUNT  + 1) * 5);
        case 4:  return Words4.W.substring( (idx % Words4.COUNT)  * 5, (idx % Words4.COUNT  + 1) * 5);
        case 5:  return Words5.W.substring( (idx % Words5.COUNT)  * 5, (idx % Words5.COUNT  + 1) * 5);
        case 6:  return Words6.W.substring( (idx % Words6.COUNT)  * 5, (idx % Words6.COUNT  + 1) * 5);
        case 7:  return Words8.W.substring( (idx % Words8.COUNT)  * 5, (idx % Words8.COUNT  + 1) * 5);
        case 8:  return Words9.W.substring( (idx % Words9.COUNT)  * 5, (idx % Words9.COUNT  + 1) * 5);
        case 9:  return Words10.W.substring((idx % Words10.COUNT) * 5, (idx % Words10.COUNT + 1) * 5);
        case 10: return Words11.W.substring((idx % Words11.COUNT) * 5, (idx % Words11.COUNT + 1) * 5);
        case 11: return Words12.W.substring((idx % Words12.COUNT) * 5, (idx % Words12.COUNT + 1) * 5);
        case 12: return Words13.W.substring((idx % Words13.COUNT) * 5, (idx % Words13.COUNT + 1) * 5);
        case 13: return Words14.W.substring((idx % Words14.COUNT) * 5, (idx % Words14.COUNT + 1) * 5);
        case 14: return Words15.W.substring((idx % Words15.COUNT) * 5, (idx % Words15.COUNT + 1) * 5);
        case 15: return Words16.W.substring((idx % Words16.COUNT) * 5, (idx % Words16.COUNT + 1) * 5);
        case 16: return Words17.W.substring((idx % Words17.COUNT) * 5, (idx % Words17.COUNT + 1) * 5);
        case 17: return Words18.W.substring((idx % Words18.COUNT) * 5, (idx % Words18.COUNT + 1) * 5);
        case 18: return Words19.W.substring((idx % Words19.COUNT) * 5, (idx % Words19.COUNT + 1) * 5);
        case 19: return Words20.W.substring((idx % Words20.COUNT) * 5, (idx % Words20.COUNT + 1) * 5);
        case 20: return Words21.W.substring((idx % Words21.COUNT) * 5, (idx % Words21.COUNT + 1) * 5);
        case 21: return Words22.W.substring((idx % Words22.COUNT) * 5, (idx % Words22.COUNT + 1) * 5);
        case 22: return Words23.W.substring((idx % Words23.COUNT) * 5, (idx % Words23.COUNT + 1) * 5);
        default: // should never happen, but fall back to Words0
            return Words0.W.substring( (idx % Words0.COUNT)  * 5, (idx % Words0.COUNT  + 1) * 5);
    }
}

    private void newGame() {
        // choose a random word index from the total count
        int idx = Math.abs(rng.nextInt()) % WORDS_LENGTH;
        targetWord  = pickWord(idx);
        guesses     = new String[MAX_GUESSES];
        hintColors  = new char[MAX_GUESSES][WORD_LENGTH];
        guessCount  = 0;
        gameOver    = false;
        won         = false;
        canvas.repaint();
    }

    // --- Compute hints ---
    private char[] computeHints(String guess) {
        char[] hints     = new char[WORD_LENGTH];
        char[] target    = targetWord.toCharArray();
        char[] guessArr  = guess.toCharArray();
        boolean[] tUsed  = new boolean[WORD_LENGTH];
        boolean[] gUsed  = new boolean[WORD_LENGTH];

        for (int i = 0; i < WORD_LENGTH; i++) {
            if (guessArr[i] == target[i]) {
                hints[i]  = 'G';
                tUsed[i]  = true;
                gUsed[i]  = true;
            }
        }
        for (int i = 0; i < WORD_LENGTH; i++) {
            if (gUsed[i]) continue;
            hints[i] = 'X';
            for (int j = 0; j < WORD_LENGTH; j++) {
                if (!tUsed[j] && guessArr[i] == target[j]) {
                    hints[i]  = 'Y';
                    tUsed[j]  = true;
                    break;
                }
            }
        }
        return hints;
    }

    // --- Open input TextBox ---
    private void openInput() {
        inputBox = new TextBox("Enter guess", "", WORD_LENGTH, TextField.ANY);
        inputBox.setMaxSize(WORD_LENGTH);

        cmdOk   = new Command("OK",   Command.OK,   1);
        cmdBack = new Command("Back", Command.BACK, 2);
        inputBox.addCommand(cmdOk);
        inputBox.addCommand(cmdBack);
        inputBox.setCommandListener(this);

        midlet.getDisplay().setCurrent(inputBox);
    }

    // --- Check if word is valid ---
    private boolean isValidWord(String word) {
        for (int i = 0; i < WORDS_LENGTH / WORD_LENGTH; i++) {
            if (pickWord(i).equals(word)) {
                return true;
            }
        }
        return false;
    }   

    // --- Submit a guess ---
    private void submitGuess(String raw) {
        String guess = raw.trim().toUpperCase();

        if (guess.length() != WORD_LENGTH) {
            showAlert("Invalid", "Must be " + WORD_LENGTH + " letters.", canvas);
            return;
        }
        if (!isValidWord(guess)) {
            showAlert("Invalid", "Not in word list.", canvas);
            return;
        }
        for (int i = 0; i < guess.length(); i++) {
            char c = guess.charAt(i);
            if (c < 'A' || c > 'Z') {
                showAlert("Invalid", "Letters only.", canvas);
                return;
            }
        }

        guesses[guessCount]    = guess;
        hintColors[guessCount] = computeHints(guess);
        guessCount++;

        if (guess.equals(targetWord)) {
            gameOver = true;
            won      = true;
        } else if (guessCount >= MAX_GUESSES) {
            gameOver = true;
        }

        midlet.getDisplay().setCurrent(canvas);
        canvas.repaint();
    }

    private void showAlert(String title, String msg, Displayable next) {
        Alert a = new Alert(title, msg, null, AlertType.WARNING);
        a.setTimeout(2000);
        midlet.getDisplay().setCurrent(a, next);
    }

    // --- CommandListener ---
    public void commandAction(Command c, Displayable d) {
        if (d == canvas) {
            if (c == cmdGuess && !gameOver) {
                openInput();
            } else if (c == cmdNew) {
                newGame();
                midlet.getDisplay().setCurrent(canvas);
            } else if (c == cmdQuit) {
                midlet.quit();
            }
        } else if (d == inputBox) {
            if (c.getCommandType() == Command.OK) {
                submitGuess(inputBox.getString());
            } else if (c.getCommandType() == Command.BACK) {
                midlet.getDisplay().setCurrent(canvas);
            }
        }
    }

    public Canvas getCanvas() {
        return canvas;
    }

    // --- Inner Canvas class ---
    private class WordleCanvas extends Canvas implements CommandListener {

        private WordleCanvas() {
            setFullScreenMode(true);

            cmdGuess = new Command("Guess", Command.OK,     1);
            cmdNew   = new Command("New",   Command.SCREEN, 2);
            cmdQuit  = new Command("Quit",  Command.EXIT,   3);

            addCommand(cmdGuess);
            addCommand(cmdNew);
            addCommand(cmdQuit);
            setCommandListener(this);
        }

        public void commandAction(Command c, Displayable d) {
            WordleGame.this.commandAction(c, d);
        }

        protected void paint(Graphics g) {
            int screenW = getWidth();
            int screenH = getHeight();

            // Background
            g.setColor(COLOR_BG);
            g.fillRect(0, 0, screenW, screenH);

            // Title
            Font titleFont = Font.getFont(Font.FACE_PROPORTIONAL, Font.STYLE_BOLD, Font.SIZE_MEDIUM);
            g.setFont(titleFont);
            g.setColor(COLOR_TEXT);
            g.drawString("WORDLE", screenW / 2, 4, Graphics.TOP | Graphics.HCENTER);

            // Divider line
            g.setColor(0x3A3A3C);
            g.drawLine(0, titleFont.getHeight() + 6, screenW, titleFont.getHeight() + 6);

            // --- Grid layout ---
            int tileSize    = (screenW - 40) / WORD_LENGTH; // tile width
            if (tileSize > 36) tileSize = 36;               // cap size
            int tileGap     = 4;
            int gridW       = WORD_LENGTH * tileSize + (WORD_LENGTH - 1) * tileGap;
            int gridH       = MAX_GUESSES * tileSize + (MAX_GUESSES - 1) * tileGap;
            int gridX       = (screenW - gridW) / 2;
            int gridY       = titleFont.getHeight() + 14;

            Font letterFont = Font.getFont(Font.FACE_PROPORTIONAL, Font.STYLE_BOLD, Font.SIZE_LARGE);
            g.setFont(letterFont);

            for (int row = 0; row < MAX_GUESSES; row++) {
                for (int col = 0; col < WORD_LENGTH; col++) {
                    int x = gridX + col * (tileSize + tileGap);
                    int y = gridY + row * (tileSize + tileGap);

                    // Tile background color
                    if (guesses[row] == null) {
                        // Empty tile — highlight current row
                        if (row == guessCount && !gameOver) {
                            g.setColor(COLOR_CURSOR);
                        } else {
                            g.setColor(COLOR_EMPTY);
                        }
                    } else {
                        char hint = hintColors[row][col];
                        if (hint == 'G')      g.setColor(COLOR_GREEN);
                        else if (hint == 'Y') g.setColor(COLOR_YELLOW);
                        else                  g.setColor(COLOR_GRAY);
                    }
                    g.fillRoundRect(x, y, tileSize, tileSize, 6, 6);

                    // Letter
                    if (guesses[row] != null) {
                        g.setColor(COLOR_TEXT);
                        String letter = String.valueOf(guesses[row].charAt(col));
                        int lx = x + tileSize / 2;
                        int ly = y + (tileSize - letterFont.getHeight()) / 2;
                        g.drawString(letter, lx, ly, Graphics.TOP | Graphics.HCENTER);
                    }
                }
            }

            // --- Status message below grid ---
            Font smallFont = Font.getFont(Font.FACE_PROPORTIONAL, Font.STYLE_PLAIN, Font.SIZE_SMALL);
            g.setFont(smallFont);
            int msgY = gridY + gridH + 10;

            if (gameOver) {
                if (won) {
                    g.setColor(COLOR_WIN);
                    g.drawString("You got it in " + guessCount + "!",
                        screenW / 2, msgY, Graphics.TOP | Graphics.HCENTER);
                } else {
                    g.setColor(COLOR_LOSE);
                    g.drawString("Word: " + targetWord,
                        screenW / 2, msgY, Graphics.TOP | Graphics.HCENTER);
                }
            } else {
                g.setColor(COLOR_TEXT);
                g.drawString("Guess " + (guessCount + 1) + " of " + MAX_GUESSES,
                    screenW / 2, msgY, Graphics.TOP | Graphics.HCENTER);
            }
        }
    }
}